language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: f1a6ac4bb3ab455ca676423ab7284a98a338a657
local_dir: dist
on:
  branch: master
